// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ignore: avoid_classes_with_only_static_members
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe2Gb3wYCnJAjAVr0Me4zP7m9OF9XMYX4',
    appId: '1:36819004997:android:9585df3000f49b0da0fd2c',
    messagingSenderId: '36819004997',
    projectId: 'givemejobs-4be17',
    storageBucket: 'givemejobs-4be17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVMztHRjlorIKgpeaFlXWR1kq0NiIHYJA',
    appId: '1:36819004997:ios:fd1bea1d409f8225a0fd2c',
    messagingSenderId: '36819004997',
    projectId: 'givemejobs-4be17',
    storageBucket: 'givemejobs-4be17.appspot.com',
    iosClientId:
        '36819004997-3skiqjea5jnqqdd3c3l32cppgbqj6itl.apps.googleusercontent.com',
    iosBundleId: 'br.com.dawidoliveira.giveMeJobsApp',
  );
}
