# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Flutter action
        uses: subosito/flutter-action@v2.2.0
      - name: build apk
        run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          path: build/app/outputs/flutter-apk/app-release.apk
